/**
 * API Endpoints Registry
 * 
 * ⚠️ AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * This file is automatically generated from API files in src/api/
 * Run: bun run scripts/generate-api-endpoints.ts to regenerate
 */

export interface MethodInfo {
  method: string;
  requestType?: string;
  responseType?: string;
  mockData?: unknown;
  description?: string;
}

export interface ApiEndpoint {
  path: string;
  methods: string[];
  methodDetails?: MethodInfo[];
  description?: string;
}

export const API_ENDPOINTS: ApiEndpoint[] = [

];

/**
 * Get endpoint by path
 */
export function getEndpointByPath(path: string): ApiEndpoint | undefined {
  return API_ENDPOINTS.find((ep) => ep.path === path);
}

/**
 * Get all unique HTTP methods across all endpoints
 */
export function getAllMethods(): string[] {
  const methods = new Set<string>();
  API_ENDPOINTS.forEach((ep) => {
    ep.methods.forEach((method) => methods.add(method));
  });
  return Array.from(methods).sort();
}

/**
 * Get method details for a specific endpoint and method
 */
export function getMethodDetails(path: string, method: string): MethodInfo | undefined {
  const endpoint = API_ENDPOINTS.find((ep) => ep.path === path);
  return endpoint?.methodDetails?.find((m) => m.method === method);
}

/**
 * Get mock data for a specific endpoint and method
 */
export function getMockData(path: string, method: string): unknown | undefined {
  const methodInfo = getMethodDetails(path, method);
  return methodInfo?.mockData;
}
