/**
 * API Endpoints Registry
 * 
 * ⚠️ AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * This file is automatically generated from API files in src/api/
 * Run: bun run scripts/generate-api-endpoints.ts to regenerate
 */

export interface MethodInfo {
  method: string;
  requestType?: string;
  responseType?: string;
  mockData?: unknown;
  description?: string;
}

export interface ApiEndpoint {
  path: string;
  methods: string[];
  methodDetails?: MethodInfo[];
  description?: string;
}

export const API_ENDPOINTS: ApiEndpoint[] = [
  {
    path: "/api/dashboard/stats",
    methods: ["GET"],
    description: "Get dashboard statistics",
    methodDetails: [
            {
                  "method": "GET",
                  "responseType": "DashboardStatsResponse",
                  "mockData": {
                        "message": "Dashboard stats",
                        "data": {
                              "totalUsers": 1234,
                              "activeUsers": 567,
                              "lastUpdated": "2025-11-03T20:54:01.613Z"
                        }
                  }
            }
      ]
  },
  {
    path: "/api/hello",
    methods: ["GET", "PUT"],
    description: "Hello world endpoint",
    methodDetails: [
            {
                  "method": "GET",
                  "responseType": "HelloResponse",
                  "mockData": {
                        "message": "Hello, world!",
                        "method": "GET"
                  }
            },
            {
                  "method": "PUT",
                  "requestType": "HelloRequest",
                  "responseType": "HelloResponse",
                  "mockData": {
                        "message": "Hello, world!",
                        "method": "PUT"
                  },
                  "description": "Update hello message"
            }
      ]
  },
  {
    path: "/api/hello/:name",
    methods: ["GET"],
    description: "Hello with name parameter",
    methodDetails: [
            {
                  "method": "GET",
                  "responseType": "HelloNameResponse",
                  "mockData": {
                        "message": "Hello, Test!"
                  }
            }
      ]
  },
  {
    path: "/api/test",
    methods: ["GET", "PUT", "POST"],
    description: "Test endpoint",
    methodDetails: [
            {
                  "method": "GET",
                  "responseType": "TestResponse",
                  "mockData": {
                        "message": "Hello, world!",
                        "method": "GET"
                  }
            },
            {
                  "method": "PUT",
                  "requestType": "TestRequest",
                  "responseType": "TestResponse",
                  "mockData": {
                        "message": "Hello, world!",
                        "method": "PUT"
                  },
                  "description": "Update test item"
            },
            {
                  "method": "POST",
                  "requestType": "TestRequest",
                  "responseType": "TestResponse",
                  "mockData": {
                        "message": "Created: test item!",
                        "method": "POST"
                  },
                  "description": "Create test item"
            }
      ]
  },
  {
    path: "/api/test/:name",
    methods: ["GET"],
    description: "Test with name parameter",
    methodDetails: [
            {
                  "method": "GET",
                  "responseType": "TestNameResponse",
                  "mockData": {
                        "message": "Hello, Test!"
                  }
            }
      ]
  }
];

/**
 * Get endpoint by path
 */
export function getEndpointByPath(path: string): ApiEndpoint | undefined {
  return API_ENDPOINTS.find((ep) => ep.path === path);
}

/**
 * Get all unique HTTP methods across all endpoints
 */
export function getAllMethods(): string[] {
  const methods = new Set<string>();
  API_ENDPOINTS.forEach((ep) => {
    ep.methods.forEach((method) => methods.add(method));
  });
  return Array.from(methods).sort();
}

/**
 * Get method details for a specific endpoint and method
 */
export function getMethodDetails(path: string, method: string): MethodInfo | undefined {
  const endpoint = API_ENDPOINTS.find((ep) => ep.path === path);
  return endpoint?.methodDetails?.find((m) => m.method === method);
}

/**
 * Get mock data for a specific endpoint and method
 */
export function getMockData(path: string, method: string): unknown | undefined {
  const methodInfo = getMethodDetails(path, method);
  return methodInfo?.mockData;
}
