/**
 * Generated by @openapi-codegen
 *
 * @version 0.0.1
 */
export type CreateTrustMarkRequest = {
  /**
   * The entity the Trust Mark applies to.
   *
   * @maxLength 2048
   * @minLength 10
   * @example http://localhost:8080/trust-mark-holder
   */
  sub: string;
  /**
   * Unique identifier of the Trust Mark Type. Should be collision-resistant across federations.
   *
   * @maxLength 2048
   * @minLength 10
   * @example http://localhost:8080/trust-mark-types/exampleType
   */
  trust_mark_id: string;
  /**
   * Optional URL to a logo for the Trust Mark entity.
   *
   * @format uri
   * @example https://example.com/logo
   */
  logo_uri?: string;
  /**
   * Optional expiration time of the Trust Mark in seconds since the epoch
   */
  exp?: number;
  /**
   * Optional URL referring to human-readable information about the issuance of the Trust Mark.
   *
   * @format uri
   */
  ref?: string;
  /**
   * Optional delegation claim as a JWT that delegates the right to issue this Trust Mark
   */
  delegation?: string;
  /**
   * If true, the request will be executed but not persisted.
   *
   * @example false
   */
  dryRun?: boolean;
  /**
   * The time for the trust mark was issued.
   *
   * @format int32
   */
  iat?: number;
};
