/**
 * Generated by @openapi-codegen
 *
 * @version 0.0.1
 */
import type * as Schemas from "./apiSchemas";

export type BadRequestError = Schemas.ErrorResponse;

export type UnauthorizedError = Schemas.ErrorResponse;

export type ForbiddenError = Schemas.ErrorResponse;

export type ServerError = Schemas.ErrorResponse;

export type NotFoundError = Schemas.ErrorResponse;
