/**
 * Generated by @openapi-codegen
 *
 * @version 0.0.1
 */
export type AccountsResponse = {
  accounts: Account[];
};

export type Account = {
  /**
   * The unique identifier for the account.
   *
   * @format uuid
   * @example 123e4567-e89b-12d3-a456-426614174000
   */
  id: string;
  /**
   * The username of the account.
   *
   * @example acmecorp
   */
  username: string;
  /**
   * The identifier of the account.
   *
   * @pattern ^https?:\/\/.*$
   * @format uri
   * @example https://www.example.com/oidf
   */
  identifier?: string;
};

export type AuthorityHintsResponse = {
  authorityHints: AuthorityHint[];
};

export type AuthorityHint = {
  /**
   * @format uuid
   */
  id: string;
  identifier: string;
  /**
   * @format uuid
   */
  accountId: string;
};

export type AccountJwksResponse = {
  jwks: AccountJwk[];
};

export type Jwk = {
  /**
   * The key type (e.g., EC).
   *
   * @example EC
   */
  kty: string;
  /**
   * The elliptic curve used (only for EC keys).
   *
   * @example P-256
   */
  crv?: string | null;
  /**
   * The key ID.
   *
   * @example 12345
   */
  kid: string;
  /**
   * The X coordinate for EC keys (optional).
   *
   * @example o-7zraXKDaoBte2PsuTXo-MSLzsyWdAElNptGgI4aH8
   */
  x?: string | null;
  /**
   * The Y coordinate for EC keys (optional).
   *
   * @example Xr_wCzJ1XnsgAIV5qHruzSwaNnwy87UjmevVklTpIv8
   */
  y?: string | null;
  /**
   * The modulus for RSA keys.
   *
   * @example modulus_value
   */
  n?: string | null;
  /**
   * The exponent for RSA keys.
   *
   * @example AQAB
   */
  e?: string | null;
  /**
   * The algorithm associated with the key.
   *
   * @example ES256
   */
  alg?: string | null;
  /**
   * The intended use of the key (e.g., sig, enc).
   *
   * @example sig
   */
  use?: string | null;
  /**
   * A URL that points to an X.509 public key certificate or certificate chain.
   *
   * @format uri
   * @example https://example.com/cert.pem
   */
  x5u?: string | null;
  /**
   * The X.509 certificate chain.
   */
  x5c?: string[] | null;
  /**
   * The SHA-1 thumbprint of the X.509 certificate.
   *
   * @example dGhpcyBpcyBqdXN0IGEgdGh1bWJwcmludA
   */
  x5t?: string | null;
  /**
   * The SHA-256 thumbprint of the X.509 certificate.
   *
   * @example sM4KhEI1Y2Sb6-EVr6tJabmJuoP-ZE...
   */
  x5tS256?: string | null;
};

export type BaseStatement = {
  /**
   * The Entity Identifier of the issuer of the Entity Statement.
   */
  iss: string;
  /**
   * The Entity Identifier of the subject.
   */
  sub: string;
  /**
   * Expiration time after which the statement MUST NOT be accepted for processing.
   */
  exp: number;
  /**
   * The time the statement was issued.
   *
   * @format int32
   */
  iat: number;
  jwks: BaseStatementJwks;
  metadata?: {
    [key: string]: any;
  };
  metadata_policy?: {
    [key: string]: any;
  };
  crit?: string[];
};

export type CreateAccount = {
  /**
   * The username of the account.
   *
   * @maxLength 32
   * @minLength 1
   * @example acmeco
   */
  username: string;
  /**
   * The identifier of the tenant account.
   *
   * @example https://www.example.com/oidf
   */
  identifier?: string;
};

export type CreateAuthorityHint = {
  /**
   * The identifier of the authority hint.
   *
   * @maxLength 2048
   * @minLength 10
   */
  identifier: string;
};

export type CreateCrit = {
  /**
   * A critical claims that must be understood and processed.
   */
  claim: string;
};

/**
 * @example {"kmsKeyRef":"my-example-key","signatureAlgorithm":"ES256"}
 */
export type CreateKey = {
  /**
   * The Key Management System to use. Needs to be a supported and configured KMS!
   *
   * @example memory
   */
  kms?: string;
  /**
   * The KMS Key reference/name you want to use. Not every KMS supports this feature!
   *
   * @example my-key
   */
  kmsKeyRef?: string;
  signatureAlgorithm?: SignatureAlgorithm;
};

/**
 * The signature algorithm to use in JOSE/JWA format
 *
 * @default ES256
 */
export type SignatureAlgorithm = "ES256" | "ES384" | "ES512";

export type MetadataResponse = {
  metadata: Metadata[];
};

export type CreateMetadata = {
  /**
   * The metadata key.
   *
   * @example openid_relying_party
   */
  key: string;
  /**
   * The metadata object.
   */
  metadata: {
    [key: string]: any;
  };
};

export type CreateMetadataPolicy = {
  /**
   * The metadata policy key.
   *
   * @example openid_relying_party
   */
  key: string;
  /**
   * The metadata policy object.
   */
  policy: {
    [key: string]: any;
  };
};

export type CreateReceivedTrustMark = {
  /**
   * The Trust Mark Type identifier.
   *
   * @example https://www.example.com/oidf/trustmark/underageSafetyVerified
   */
  trust_mark_id: string;
  /**
   * The received Trust Mark JWT.
   *
   * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
   */
  jwt: string;
};

export type CreateSubordinate = {
  /**
   * The identifier of the subordinate account.
   *
   * @example https://www.example.com/subordinate
   */
  identifier: string;
};

/**
 * Data Transfer Object for creating a Trust Mark.
 */
export type CreateTrustMark = {
  /**
   * The entity the Trust Mark applies to.
   *
   * @example https://entity.example.com
   */
  sub: string;
  /**
   * Unique identifier of the Trust Mark Type. Should be collision-resistant across federations.
   *
   * @example https://trustframework.example.com/marks/12345
   */
  trust_mark_id: string;
  /**
   * Optional URL to a logo for the Trust Mark entity.
   *
   * @example https://example.com/logo.png
   */
  logo_uri?: string;
  /**
   * Optional expiration time of the Trust Mark in seconds since the epoch.
   *
   * @example 1706031234
   */
  exp?: number;
  /**
   * Optional URL referring to human-readable information about the issuance of the Trust Mark.
   *
   * @example https://trustmark-issuer.example.com/info
   */
  ref?: string;
  /**
   * Optional delegation claim as a JWT that delegates the right to issue this Trust Mark.
   *
   * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
   */
  delegation?: string;
};

export type CreateTrustMarkResult = {
  /**
   * Unique ID of the Trust Mark.
   *
   * @format uuid
   * @example 123e4567-e89b-12d3-a456-426614174000
   */
  id?: string;
  /**
   * The id of the trustmark owner account.
   *
   * @format uuid
   * @example 123e4567-e89b-12d3-a456-426614174000
   */
  account_id: string;
  /**
   * The id of the trustmark type.
   *
   * @format uuid
   */
  trust_mark_id: string;
  /**
   * The entity the Trust Mark applies to.
   *
   * @example https://entity.example.com
   */
  sub: string;
  /**
   * The JWT of the Trust Mark.
   */
  trust_mark_value: string;
  /**
   * Time when the signed JWT was issued, using the time format defined for the iat claim in RFC7519.
   */
  iat: number;
  exp?: number;
};

export type TrustMarksResponse = {
  trustMarks?: TrustMark[];
};

export type CreateTrustMarkType = {
  /**
   * The unique identifier for the Trust Mark Type.
   *
   * @example https://www.example.com/oidf/trustmark/underageSafetyVerified
   */
  identifier: string;
};

export type CreateTrustMarkTypeIssuerRequest = {
  /**
   * The entity identifier for the Trust Mark Type Issuer.
   *
   * @example https://www.example.com/oidf
   */
  identifier: string;
};

export type EntityConfigurationStatement = BaseStatement & {
  authority_hints?: string[];
  /**
   * An array of JSON objects, each representing a Trust Mark.
   */
  trust_marks?: TrustMark[];
  trust_mark_issuers?: TrustMarkIssuers;
  trust_mark_owners?: TrustMarkOwners;
};

export type ErrorResponse = {
  status?: number;
  error: string;
  /**
   * A human-readable short text describing the error.
   */
  message: string;
  timestamp?: number;
};

export type FederationEntityMetadata = {
  /**
   * URL for the federation fetch endpoint.
   *
   * @format uri
   */
  federation_fetch_endpoint?: string;
  /**
   * URL for the federation list endpoint.
   *
   * @format uri
   */
  federation_list_endpoint?: string;
  /**
   * URL for the federation resolve endpoint.
   *
   * @format uri
   */
  federation_resolve_endpoint?: string;
  /**
   * URL for the federation trust mark status endpoint.
   *
   * @format uri
   */
  federation_trust_mark_status_endpoint?: string;
  /**
   * URL for the federation trust mark list endpoint.
   *
   * @format uri
   */
  federation_trust_mark_list_endpoint?: string;
  /**
   * URL for the federation trust mark endpoint.
   *
   * @format uri
   */
  federation_trust_mark_endpoint?: string;
  /**
   * URL for the federation historical keys endpoint.
   *
   * @format uri
   */
  federation_historical_keys_endpoint?: string;
  /**
   * Organization name.
   */
  organization_name?: string;
  /**
   * URL for the homepage of the organization.
   *
   * @format uri
   */
  homepage_uri?: string;
};

export type FederationHistoricalKeysResponse = {
  /**
   * The Entity's Entity Identifier.
   *
   * @format uri
   */
  iss: string;
  /**
   * Time when the signed JWT was issued, using the time format defined for the iat claim in RFC7519.
   */
  iat: number;
  keys: HistoricalKey[];
};

export type HistoricalKey = Jwk & {
  /**
   * The time the key was issued.
   *
   * @format int32
   * @example 1629936000
   */
  iat?: number;
  /**
   * The time the key will expire.
   *
   * @format int32
   * @example 1632528000
   */
  exp?: number;
  revoked?: JwkRevoked;
};

export type AccountJwk = Jwk & {
  /**
   * The unique identifier for the JWK record.
   *
   * @format uuid
   * @example 123e4567-e89b-12d3-a456-426614174000
   */
  id: string;
  /**
   * The Key Management System
   *
   * @example memory
   */
  kms?: string;
  /**
   * The KMS Key reference (the id of the key in the KMS) if supported
   *
   * @example my-key
   */
  kmsKeyRef?: string;
  /**
   * The ID of the account associated with this JWK.
   *
   * @format uuid
   * @example 123e4567-e89b-12d3-a456-426614174000
   */
  accountId?: string;
  /**
   * The timestamp when the JWK was revoked, if applicable.
   *
   * @format date-time
   * @example "2024-09-01T12:34:56.000Z"
   */
  revokedAt?: string | null;
  /**
   * The reason for revoking the JWK, if applicable.
   *
   * @example Key compromise
   */
  revokedReason?: string | null;
  /**
   * The timestamp when the JWK was created.
   *
   * @format date-time
   * @example "2024-08-06T12:34:56.000Z"
   */
  createdAt?: string | null;
};

export type JwkRevoked = {
  /**
   * @format date-time
   */
  revokedAt: string;
  reason?: string;
};

export type JwkWithPrivateKey = Jwk & {
  /**
   * The private key value (for RSA and EC keys).
   */
  d?: string | null;
  /**
   * The first prime factor (for RSA private key).
   */
  p?: string | null;
  /**
   * The second prime factor (for RSA private key).
   */
  q?: string | null;
  /**
   * The first factor CRT exponent (for RSA private key).
   */
  dp?: string | null;
  /**
   * The second factor CRT exponent (for RSA private key).
   */
  dq?: string | null;
  /**
   * The first CRT coefficient (for RSA private key).
   *
   * @example base64url_encoded_qi
   */
  qi?: string | null;
};

/**
 * A JWT (JSON Web Token) object, composed of a header, payload, and signature.
 */
export type Jwt = {
  header: JwtHeader;
  /**
   * The payload of the JWT, typically containing claims (as JSON key-value pairs).
   */
  payload: {
    [key: string]: any;
  };
  /**
   * The cryptographic signature of the JWT.
   */
  signature: string;
};

export type JwtHeader = {
  /**
   * The algorithm used to sign the JWT (e.g., RS256)
   */
  alg?: string;
  /**
   * The unique identifier for the key used to sign the JWT
   */
  kid: string;
  /**
   * The type of token (optional, e.g., "entity-statement+jwt")
   */
  typ?: string | null;
  /**
   * An optional list of trust chain certificates or keys
   */
  trust_chain?: string[] | null;
};

export type Log = {
  /**
   * Unique identifier for the log entry
   *
   * @format int64
   */
  id: number;
  /**
   * The severity level of the log entry
   */
  severity: "Verbose" | "Debug" | "Info" | "Warn" | "Error" | "Assert";
  /**
   * The log message
   */
  message: string;
  /**
   * The tag/category of the log entry
   */
  tag: string;
  /**
   * The timestamp when the event occurred (epoch milliseconds)
   *
   * @format int64
   */
  timestamp: number;
  /**
   * Error message if an exception occurred
   */
  throwable_message?: string | null;
  /**
   * Stack trace if an exception occurred
   */
  throwable_stacktrace?: string | null;
  /**
   * Additional contextual information
   */
  metadata?: {
    [key: string]: any;
  } | null;
};

export type Metadata = {
  /**
   * The unique identifier for the Metadata record.
   *
   * @format uuid
   * @example 123e4567-e89b-12d3-a456-426614174000
   */
  id?: string;
  /**
   * The ID of the account associated with this Metadata.
   *
   * @format uuid
   * @example 123e4567-e89b-12d3-a456-426614174000
   */
  accountId?: string;
  /**
   * The key of the metadata.
   *
   * @example openid_relying_party
   */
  key?: string;
  metadata?: {
    [key: string]: any;
  };
  /**
   * The timestamp when the Metadata was created.
   *
   * @format date-time
   * @example "2024-08-06T12:34:56.000Z"
   */
  createdAt?: string;
  /**
   * The timestamp when the Metadata was deleted.
   *
   * @format date-time
   * @example "2024-08-06T12:34:56.000Z"
   */
  deletedAt?: string | null;
};

export type MetadataPolicy = {
  /**
   * The unique identifier for the Metadata Policy record.
   *
   * @format uuid
   * @example 123e4567-e89b-12d3-a456-426614174000
   */
  id?: string;
  /**
   * The ID of the account associated with this Metadata Policy.
   *
   * @format uuid
   * @example 123e4567-e89b-12d3-a456-426614174000
   */
  accountId?: string;
  /**
   * The key of the Metadata Policy.
   *
   * @example openid_relying_party
   */
  key?: string;
  policy?: {
    [key: string]: any;
  };
  /**
   * The timestamp when the Metadata Policy was created.
   *
   * @format date-time
   * @example "2024-08-06T12:34:56.000Z"
   */
  createdAt?: string;
  /**
   * The timestamp when the Metadata Policy was deleted.
   *
   * @format date-time
   * @example "2024-08-06T12:34:56.000Z"
   */
  deletedAt?: string | null;
};

export type MetadataPolicyResponse = {
  metadataPolicies: MetadataPolicy[];
};

export type PublishStatementRequest = {
  /**
   * The KMS Key reference to use. If not provided the first key for the account will be used unless the kid parameter is set
   *
   * @example my-jwk-name
   */
  kmsKeyRef?: string;
  /**
   * The kid of the key to use. If a kmsKeyRef is provided it will always take priority
   *
   * @example 1234
   */
  kid?: string;
  /**
   * If true, the request will be executed but not persisted.
   *
   * @example false
   */
  dryRun?: boolean;
};

export type ReceivedTrustMarksResponse = {
  receivedTrustMarks: ReceivedTrustMark[];
};

export type CreateReceivedTrustMarkResponse = {
  /**
   * The identifier of the Trust Mark Type.
   *
   * @example https://example.com/trust-mark-type
   */
  trustMarkTypeId: string;
  /**
   * The JWT representing the received Trust Mark.
   */
  jwt: string;
};

export type ReceivedTrustMark = {
  /**
   * The unique identifier for the received Trust Mark.
   *
   * @format uuid
   * @example 123e4567-e89b-12d3-a456-426614174000
   */
  id?: string;
  /**
   * The account ID of the Trust Mark holder.
   *
   * @format uuid
   * @example 123e4567-e89b-12d3-a456-426614174000
   */
  accountId?: string;
  /**
   * The Trust Mark type identifier.
   *
   * @example https://www.example.com/oidf/trustmark/underageSafetyVerified
   */
  trust_mark_id?: string;
  /**
   * The received Trust Mark JWT.
   *
   * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
   */
  jwt?: string;
  /**
   * The timestamp when the Trust Mark was created.
   *
   * @format date-time
   * @example "2024-12-01T12:00:00.000Z"
   */
  createdAt?: string;
};

export type ResolveResponse = {
  /**
   * Entity Identifier of the issuer of the resolve response.
   *
   * @format date-time
   */
  iss: string;
  /**
   * Entity Identifier of the subject of the resolve response.
   *
   * @format date-time
   */
  sub: string;
  /**
   * Time when this resolution was issued. This is expressed as Seconds Since the Epoch.
   *
   * @format date-time
   */
  iat: string;
  /**
   * Time when this resolution is no longer valid. This is expressed as Seconds Since the Epoch.
   *
   * @format date-time
   */
  exp: string;
  /**
   * Additional contextual information
   */
  metadata: {
    [key: string]: any;
  } | null;
  trust_marks?: TrustMark[];
  trust_chain?: string[];
};

export type SubordinatesResponse = {
  subordinates: Subordinate[];
};

export type Subordinate = {
  /**
   * The unique identifier of the subordinate.
   *
   * @format uuid
   * @example 123e4567-e89b-12d3-a456-426614174000
   */
  id: string;
  /**
   * The ID of the account associated with this subordinate.
   *
   * @format uuid
   * @example 123e4567-e89b-12d3-a456-426614174000
   */
  accountId: string;
  /**
   * The unique identifier for the subordinate.
   *
   * @example https://www.example.com/subordinate
   */
  identifier: string;
  /**
   * The timestamp when the subordinate was created.
   *
   * @format date-time
   * @example "2023-08-21T14:52:00.000Z"
   */
  createdAt: string;
  /**
   * The timestamp when the subordinate was deleted, if applicable.
   *
   * @format date-time
   * @example "2024-08-21T14:52:00.000Z"
   */
  deletedAt?: string | null;
};

export type SubordinateJwksResponse = {
  jwks: SubordinateJwk[];
};

export type SubordinateJwk = {
  /**
   * The unique identifier for the Subordinate key record.
   *
   * @format uuid
   * @example 123e4567-e89b-12d3-a456-426614174000
   */
  id: string;
  /**
   * The ID of the subordinated account associated with this key.
   *
   * @format uuid
   * @example 123e4567-e89b-12d3-a456-426614174000
   */
  subordinateId: string;
  key: Jwk;
  /**
   * The timestamp when the key was created.
   *
   * @format date-time
   * @example "2024-08-06T12:34:56.000Z"
   */
  createdAt?: string;
};

export type SubordinateMetadataResponse = {
  subordinateMetadata?: SubordinateMetadata[];
};

export type SubordinateMetadata = {
  /**
   * The unique identifier for the Subordinate Metadata record.
   *
   * @format uuid
   * @example 123e4567-e89b-12d3-a456-426614174000
   */
  id: string;
  /**
   * The ID of the account associated with this Metadata.
   *
   * @format uuid
   * @example 123e4567-e89b-12d3-a456-426614174000
   */
  accountId: string;
  /**
   * The ID of the subordinate associated with this Metadata.
   *
   * @format uuid
   * @example 123e4567-e89b-12d3-a456-426614174000
   */
  subordinateId: string;
  /**
   * The key of the metadata.
   *
   * @example openid_relying_party
   */
  key: string;
  metadata: {
    [key: string]: any;
  };
  /**
   * The timestamp when the Metadata was created.
   *
   * @format date-time
   * @example "2024-08-06T12:34:56.000Z"
   */
  createdAt: string;
  /**
   * The timestamp when the Metadata was deleted.
   *
   * @format date-time
   * @example "2024-08-06T12:34:56.000Z"
   */
  deletedAt?: string | null;
};

export type SubordinateStatement = {
  /**
   * The Entity Identifier of the issuer of the Entity Statement.
   */
  iss: string;
  /**
   * The Entity Identifier of the subject.
   */
  sub: string;
  /**
   * Expiration time after which the statement MUST NOT be accepted for processing.
   */
  exp: number;
  /**
   * The time the statement was issued.
   *
   * @format int32
   */
  iat: number;
  jwks: BaseStatementJwks;
  metadata?: {
    [key: string]: any;
  };
  metadata_policy?: {
    [key: string]: any;
  };
  crit?: string[];
  metadata_policy_crit?: {
    [key: string]: any;
  };
  /**
   * String containing the fetch endpoint URL from which the Entity Subordinate Statement was issued.
   *
   * @format uri
   */
  source_endpoint?: string;
};

export type SubordinateStatementPayload = {
  /**
   * The Entity Identifier of the issuer of the Entity Statement.
   */
  iss: string;
  /**
   * The Entity Identifier of the subject.
   */
  sub: string;
  /**
   * Expiration time after which the statement MUST NOT be accepted for processing.
   */
  exp: number;
  /**
   * The time the statement was issued.
   *
   * @format int32
   */
  iat: number;
  jwks: BaseStatementJwks;
  metadata?: {
    [key: string]: any;
  };
  metadata_policy?: {
    [key: string]: any;
  };
  crit?: string[];
  metadata_policy_crit?: {
    [key: string]: any;
  };
  /**
   * String containing the fetch endpoint URL from which the Entity Subordinate Statement was issued.
   *
   * @format uri
   */
  source_endpoint?: string;
};

export type StatusResponse = {
  /**
   * The current status of the node.
   *
   * @example UP
   */
  status?: string;
};

export type TrustMark = {
  /**
   * The Trust Mark identifier. It MUST be the same value as the id claim contained in the Trust Mark JWT.
   *
   * @example example-trust-mark-id
   */
  id: string;
  /**
   * A signed JSON Web Token that represents a Trust Mark.
   *
   * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
   */
  trust_mark: string;
};

export type TrustMarkIssuersResponse = {
  issuers: TrustMarkIssuer[];
};

export type TrustMarkIssuer = {
  /**
   * Unique ID of the Trust Mark Issuer for this type.
   *
   * @format uuid
   * @example 123e4567-e89b-12d3-a456-426614174000
   */
  id?: string;
  /**
   * The id of the trustmark type
   *
   * @format uuid
   * @example 123e4567-e89b-12d3-a456-426614174000
   */
  trustMarkTypeId?: string;
  /**
   * The unique identifier for the issuer added to the trustmark.
   *
   * @example https://www.example.com
   */
  issuer?: string;
  /**
   * The timestamp when the Trust Mark Type was created.
   *
   * @format date-time
   * @example "2024-12-01T12:00:00.000Z"
   */
  createdAt?: string;
  /**
   * The timestamp when the Trust Mark Type was deleted.
   *
   * @format date-time
   */
  deletedAt?: string;
};

/**
 * A mapping of trust mark identifiers to their associated issuers.
 *
 * @example {"https://openid.net/certification/op":["https://example-issuer1.com","https://example-issuer2.com"],"https://refeds.org/wp-content/uploads/2016/01/Sirtfi-1.0.pdf":["https://swamid.se"]}
 */
export type TrustMarkIssuers = {
  [key: string]: string[];
};

/**
 * @example {"https://refeds.org/wp-content/uploads/2016/01/Sirtfi-1.0.pdf":{"sub":"https://refeds.org/sirtfi","jwks":{"keys":[{"alg":"RS256","e":"AQAB","kid":"key1","kmsKeyRef":"key1","kms":"memory","kty":"RSA","n":"pnXBOusEANuug6ewezb9J_...","use":"sig"}]}}}
 */
export type TrustMarkOwners = {
  [key: string]: TrustMarkOwner;
};

export type TrustMarkOwner = {
  /**
   * Identifier of the Trust Mark owner
   */
  sub?: string;
  jwks?: Jwk[];
  additionalProperties?: string;
};

/**
 * Data Transfer Object for retrieving a Trust Mark.
 */
export type TrustMarkPayload = {
  /**
   * The Trust Mark issuer.
   *
   * @example https://www.example.com/oidf
   */
  iss?: string;
  /**
   * The entity the Trust Mark applies to.
   *
   * @example https://entity.example.com
   */
  sub?: string;
  /**
   * The Trust Mark Type identifier.
   *
   * @example https://www.example.com/oidf/trustmark/underageSafetyVerified
   */
  id?: string;
  /**
   * The time the Trust Mark was issued.
   *
   * @example 1706031234
   */
  iat?: number;
  /**
   * Optional URL to a logo for the Trust Mark entity.
   *
   * @example https://example.com/logo.png
   */
  logo_uri?: string;
  /**
   * The time the Trust Mark expires.
   *
   * @example 1706031234
   */
  exp?: number;
  /**
   * Optional URL referring to human-readable information about the issuance of the Trust Mark.
   *
   * @example https://trustmark-issuer.example.com/info
   */
  ref?: string;
  /**
   * Optional delegation claim as a JWT that delegates the right to issue this Trust Mark.
   *
   * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
   */
  delegation?: string;
};

export type TrustMarkListRequest = {
  /**
   * The Trust Mark Type identifier.
   *
   * @example https://www.example.com/oidf/trustmark/underageSafetyVerified
   */
  trust_mark_id: string;
  /**
   * The entity the Trust Mark applies to.
   *
   * @example https://entity.example.com
   */
  sub?: string;
};

export type TrustMarkRequest = {
  /**
   * The Trust Mark Type identifier.
   *
   * @example https://www.example.com/oidf/trustmark/underageSafetyVerified
   */
  trust_mark_id: string;
  /**
   * The entity the Trust Mark applies to.
   *
   * @example https://entity.example.com
   */
  sub: string;
};

export type TrustMarkStatusRequest = {
  /**
   * The entity the Trust Mark applies to.
   *
   * @example https://entity.example.com
   */
  sub: string;
  /**
   * The Trust Mark Type identifier.
   *
   * @example https://www.example.com/oidf/trustmark/underageSafetyVerified
   */
  trust_mark_id: string;
  /**
   * The time the Trust Mark was issued.
   *
   * @example 1706031234
   */
  iat?: number;
};

export type TrustMarkStatusResponse = {
  /**
   * The status of the Trust Mark.
   *
   * @example true
   */
  active?: boolean;
};

export type TrustMarkTypesResponse = {
  trustMarkTypes: TrustMarkType[];
};

export type TrustMarkType = {
  /**
   * The unique identifier of the Trust Mark Type.
   *
   * @format uuid
   * @example 123e4567-e89b-12d3-a456-426614174000
   */
  id: string;
  /**
   * The unique identifier for the Trust Mark Type.
   *
   * @example https://www.example.com/oidf/trustmark/underageSafetyVerified
   */
  identifier: string;
  /**
   * The timestamp when the Trust Mark Type was created.
   *
   * @format date-time
   * @example "2024-12-01T12:00:00.000Z"
   */
  createdAt: string;
  /**
   * The timestamp when the Trust Mark Type was last updated.
   *
   * @format date-time
   * @example "2024-12-15T15:30:00.000Z"
   */
  updatedAt?: string | null;
};

export type VerifyTrustChainResponse = {
  isValid: boolean;
  errorMessage?: string;
};

export type TrustChainResolveResponse = {
  /**
   * A list of strings representing the resolved trust chain. Each string contains a JWT.
   */
  trustChain?: string[] | null;
  /**
   * Error message in case of a failure, if any.
   */
  errorMessage?: string | null;
};

export type TrustMarkValidationResponse = {
  isValid: boolean;
  errorMessage?: string;
};

export type InlineResponse200 = {
  /**
   * Unique ID of the removed Trust Mark Issuer.
   *
   * @format uuid
   */
  id?: string;
  /**
   * Identifier of the removed issuer.
   *
   * @format uuid
   */
  identifier?: string;
};

/**
 * @example {"message":"Trust Mark deleted successfully"}
 */
export type InlineResponse2001 = {
  message?: string;
};

export type InlineResponse201 = {
  /**
   * The unique identifier of the created received Trust Mark.
   *
   * @format uuid
   */
  trustMarkId?: string;
};

export type InlineResponse2002 = {
  /**
   * @example Received Trust Mark deleted successfully.
   */
  message?: string;
};

export type BaseStatementJwks = {
  keys?: Jwk[];
};
